### PR TITLE
fix for issue #324

### PR DESCRIPTION
**Pull request by sblunt**

### CODE REVIEW

**Review by semaphoreP — APPROVED** [review]
Ah, good ol' string formats. As long as it doesn't break existing tests, I'm satisfied.

**Comment by sblunt** [comment]
Oh right, tests! XD I just added another unit test so we're now testing saving/loading for both formats of IAD files we accept, which broke, so I fixed that too. I checked that .hdf5 files generated by both of those tests on a linux machine can be loaded correctly on my mac.

**Comment by semaphoreP** [comment]
Great! Looks good then. Feel free to merge

**Comment by sblunt** [comment]
Cool. Will do once @sefffal has a chance to test.

**Comment by sefffal** [comment]
All good!

**Comment by tomasstolker** [comment]
Thanks very much! Works for me as well!

**Pull request merged**
