### PR TITLE
Improve results class and basic plotting

### PR DESCRIPTION
**Pull request by henry-ngo**
This branch sets up the routines needed to interface sampler.py and results.py. It also allows for two types of plotting to occur in results.py: corner plots and orbit plots. Addresses Issue #11. Implements rationale in #49.

These plotting routines return matplotlib Figure objects for further user customization or for user to display or save. results.plot_corner() allows user to pass on any corner.corner() keyword arguments.

I've temporarily put up two PDFs so that you can see the default output on some test data (samples drawn from normal distributions based on Jason's 2016 paper on Beta Pic).

[plot_corner example output](http://planetngo.ca/orbitize_temp/test_plot_corner_output.pdf)

[plot_orbit example output](http://planetngo.ca/orbitize_temp/test_plot_orbits_output.pdf)

This PR will also update the orbital elements ordering for results.py and sampler.py (for MCMC), which is two out of four areas required as per #45.

### CODE REVIEW

**Comment by sblunt** [comment]
Hey @henry-ngo, sorry it took forever for me to answer your question. 
I like HDF5 best personally, but pickle seems a little more mainstream in astronomy unless you're really working with giant datasets. @semaphoreP what do you think?
Also, the plots look great. I'm going to poke around in your code a bit just so I understand what's going on, then I'll pull it in.

**Comment by henry-ngo** [comment]
No problem. Let me know if you have any questions or want me to comment any particular portions better!

**Comment by semaphoreP** [comment]
I'm a fan of HDF5. Pickle files I found are often 2x the size of HDF5, and I don't really like how you access pickle files. Otherwise, FITS files are also fine.

**Comment by sblunt** [comment]
Sounds good to me!

**Comment by sblunt** [comment]
Ok, @henry-ngo I think this code looks good and I'm ready to merge it in. I'll create an issue to track the method for saving results so we can close this branch.

**Pull request merged**
