### PR TITLE
Param idx labels for Results and MCMC classes

### PR DESCRIPTION
**Pull request by sblunt**
Add `param_idx` attributes to the `Results` and `MCMC` classes for debugging aid.

### CODE REVIEW

**Comment by sblunt** [comment]
@sylacour let me know what you think!

**Comment by sylacour** [comment]
Sure, I’ll look at it next week!

**Comment by sblunt** [comment]
@sylacour just a reminder to check out these changes when you have a chance. Thanks! :)

**Review by semaphoreP — APPROVED** [review]
We should merge this soon.

**Pull request merged**
