### PR TITLE
Added ``object`` column to data table 

### PR DESCRIPTION
**Pull request by henry-ngo**
To match a measurement with a particular object. Tests and sample files updated too.

### CODE REVIEW

**Comment by henry-ngo** [comment]
Looks like some integer/type checking failing in Python3. I'll get to this soon!

**Comment by sblunt** [comment]
Looks good to me once bugs are squashed!

**Comment by henry-ngo** [comment]
Sorry that I haven't had time to devote to this recently!

**Comment by sblunt** [comment]
Don’t be sorry— I didn’t even get a chance to look at it until last night.
Please take your time.

**Comment by henry-ngo** [comment]
Okay, looks like it was a pretty simple bug to squash! I had a test that was checking if one of the columns was an integer and in Python2 a check against `int` passed even if the type was actually `int64`. However, it seems like I need to explicitly check for `int64` in Python3 (which also works in Python2). 

So, when you get a chance to review, @sblunt, please merge :)

**Pull request merged**
