### PR TITLE
Fix three bugs

### PR DESCRIPTION
**Pull request by sblunt**
Issues #113, #103, #117

### CODE REVIEW

**Comment by sblunt** [comment]
Note that this PR builds on PR #125.

**Comment by semaphoreP** [comment]
Does `pa_err = sep_err/sep` return in radians, whereas PA is defined in degrees?

**Comment by henry-ngo** [comment]
Not sure if I should comment on #103 or here.  At least this line will cause a automatically link to appear in #103, right? Hopefully that github magic works lol.

It looks like you said you want to only return lnlike for both OFTI and MCMC. Also looks like the changes rename the lnpost entries in Results object to lnlike. 

But I believe the MCMC sampler will always return lnpost, not lnlike. Maybe I missed a change to sampler.py but since we are passing prior info to the MCMC sampler, all samples chosen by ptemcee will already incorporate prior info so the distribution we get in the end is actually a sample of the posterior, not the likelihood? 

I think most MCMC users would expect to get the posteriors, not the likelihoods. So I think the current implementation is fine but the naming convention could be misleading. 

But if I misunderstood the changes then please let me know!

**Comment by sblunt** [comment]
Yes, thanks for that good catch @semaphoreP. I just fixed it.

@henry-ngo, yes emcee by default returns log posterior probability, but I subtracted off the log prior probability so it should give likelihood.

**Comment by henry-ngo** [comment]
@sblunt oh okay, I see the changes now!

I don't think we need to subtract off the prior when using the Parallel Tempering MCMC sampler because it returns likelihood and prior separately, since it needs to calculate them separately for the temperatures. the `lnlikelihood` property of the ptemcee sampler should get you this! We should just grab this attribute instead.

However, for the EnsembleSampler, we don't get likelihood separately. Just thinking of an edge case for that: if the prior returns -np.inf, then this would make the likelihood be +np.inf. Although we should never have this since a location that is outside the prior would not be sampled by emcee.... Unless, the walker inadvertently started outside of the prior space and couldn't find its way back in. Then the posterior returned should be -np.inf. The prior calculated is also -np.inf. The likelihood would be `nan` here, since I think -np.inf - (-np.inf) = nan? This isn't ideal since it's a little confusing and the user can't get back the posterior by adding the prior back on. 

The ideal thing to get here would be the actual likelihood value. Perhaps we can do a check for nans in this array and then calculate the likelihood again for the steps that have this problem. This can be computationally costly and if these are outside of the prior, then maybe they are not useful anyways and the user might not know this until it spends a bunch of computational time calculating useless values. So maybe returning nans (to distinguish from -np.inf likelihoods) with a warning? Or setting nan to -np.inf with a warning?

**Comment by semaphoreP** [comment]
Henry, these are good points. It does feel a little weird to me to do Bayesian orbit fitting but only save likelihoods and not posterior probabilities. The latter does seem like the better Bayesian criteria, although frequentist metrics to assess goodness of fit using the likelihood are sometimes useful. Perhaps we should try to save both? Did we have a discussion already on whether to save both (I forget)?

**Comment by henry-ngo** [comment]
@semaphoreP : I think we talked about this a bit here and maybe at the hackathon too? @sblunt said she made a decision in the thread for Issue #103

**Comment by sblunt** [comment]
That's a good point @henry-ngo. I think returning a warning would be good. In general, it seems like a good idea to warn the user if the chains are starting outside the prior space. 

Yes, @semaphoreP here's my comment on Issue #103. Open to other ways of dealing with it though.

"I decided to just return the loglikelihood, rather than both it and the logprobability, since the results object code was getting messy with lots of try-except cases for backwards-compatibility. Users should be able to generate lnprobs without too much difficulty, and the code Junellie is working on (Issue #118) will make this more user-friendly too."

(ps. I think I treated ptemcee and emcee outputs correctly, but maybe worth checking since y'all are the MCMC experts?)

**Comment by semaphoreP** [comment]
Looks right to me. Maybe best thing to do is write a test to confirm emcee stores the likelihood (i.e., compare the lnlike in results with straight up computing the lnlike using the lnlike function)?

**Comment by henry-ngo** [comment]
Hi @sblunt 

On returning the right property from PT MCMC vs. EnsembleSampler MCMC: I think this should be a permalink to the lines of code that I woudl like to discuss: https://github.com/sblunt/orbitize/blob/4c83586698a80e0d65389a91e02355a7408189fd/orbitize/sampler.py#L490

I think Lines 492 and 493, within the `if` block when running PT should have `sampler.logprobability` changed to `sampler.loglikelihood` so that we directly get the likelihood from the sampler, instead of computing it ourselves as we do now in Lines 499-500. With this change, you can move the current prior subtraction on Line 500 to be within the `else` block. 

What you have now will still calculate the correct result. However, in the PT case, I would prefer to directly get the likelihood where possible. It will avoid potential errors where the priors are not well behaved values as I wrote above. For the emcee sampler, we can't get around it so just raising a warning should be fine.

But if you have a different reason for choosing logprobability there in Lines 492-493, I'd love to hear it!

**Comment by sblunt** [comment]
Hey all, I fixed the point Henry pointed out and added the test Jason suggested. This branch is ready to merge now! I'm going to pull in the changes then release a new version.

**Pull request merged**
