### PR TITLE
Proper motion vs epoch plotting function

### PR DESCRIPTION
**Pull request by wbalmer**
Here's a function to plot the proper motion vs time, with curves color-coded by a cbar param. Still working on a stellar absolute position plot, but this should address the 2nd point Sarah raised in #291 . Also included an example in the HGCA tutorial notebook.

### CODE REVIEW

**Comment by semaphoreP** [comment]
This looks good. I think it is worth mentioning somewhere that the trajectories aren't *exactly* what we are fitting in the likelihood, since we actually try to forward model Hip/Gaia per epoch and infer the differential proper motion. But they are close enough for visualization purposes. This is why the Hinkley+ 2023 paper only shows histograms.

**Comment by wbalmer** [comment]
Right. I'll add some disclaimer text to the be printed during the function call and included in the docstring.

**Comment by semaphoreP** [comment]
I would say putting it in the docs/tutorial would be even better. Just thinking out loud, I think a succinct way of describing it is that we're actually fitting the time-averaged proper motions and not the instantaneous ones plotted. Might be more clear than waving hands about forward modeling the per-epoch scans.

**Comment by wbalmer** [comment]
Gotcha! Let me know if that message in the function and tutorial notebook is any better.

**Comment by semaphoreP** [comment]
Looks good! Merged now.

**Pull request merged**
