### PR TITLE
Ofti time warning

### PR DESCRIPTION
**Pull request by sblunt**
Minor changes to #345. Ready to pull in with Michael's approval (and tests passing)

### CODE REVIEW

**Comment by sblunt** [comment]
@michaelkmpoon once you accept collaborator request I'll ask you to review the (minor) changes to this PR, then I'll pull it to the v3 branch.

**Comment by michaelkmpoon** [comment]
@sblunt the minor changes looks good to me! Not sure why some of the tests failed though

**Comment by sblunt** [comment]
Sweet! Tests failing is my fault I think. I've just restarted them.

**Review by michaelkmpoon — APPROVED** [review]
looks good to me!

**Pull request merged**
