### PR TITLE
Eanom optimizations

### PR DESCRIPTION
**Pull request by rjderosa**
A few modifications:

- Element, parallax and mtot vectors are now converted into (n_orbs, n_dates) arrays. A bit clunky. The alternative is to use [:, None] indexing, although that would have to be put everywhere in the code, so maybe this is neater?
- manom now wrapped between 0->2pi. This significantly changes the output for high eccentricity orbits.
- raoff, deoff and vz calculation vectorized
- eanom calculation vectorized
- Split the newton solver into its own function.
- Various modifications for consistency, and removed some unused variables.

### CODE REVIEW

**Comment by sblunt** [comment]
@rjderosa do you want to merge this PR into `master` now or iterate for a while longer?

**Comment by henry-ngo** [comment]
I'm going to add some commits to fix that missing docstring text. 

Also, to allow for an array input for `mass`, as suggested above.

**Comment by rjderosa** [comment]
I think i've finished tinkering with the eccentric anomaly stuff. It should work for when `ecc` and `Manom` are both scalars, when they are both vectors, and when `ecc` is a scalar and `Manom` is a vector. I don't think you'll ever be in a situation where you have a single mean anomaly with multiple eccentricities?

It can probably be tidied up a bit, especially if you wanted to do something more fancy that the transposing/tiling at the top to make all the arrays into shape (n_orb, n_epoch).

**Comment by henry-ngo** [comment]
Great. I'm about to commit the changes I mentioned above to this branch too.

**Comment by rjderosa** [comment]
Could we not compute ka and kb in the same way for both mass==0 and mass!=0? When it's massless `ka` will just be zero.

**Comment by henry-ngo** [comment]
@rjderosa Good point. let me check. I just kept the same structure as before since I haven't had much experience calculating RV semi-amplitudes and thought it was separate for a reason.

**Comment by henry-ngo** [comment]
Yes, you're right---passes all the tests! Updated now!

**Comment by rjderosa** [comment]
Looks as though the second equation is all you need for `ka`. We could add the functionality to fit SB2s, `k2` would just be the same equation but with the primary mass rather than the secondary (and a negative sign).

**Comment by rjderosa** [comment]
We should probably rename `m2` to something that doesn't sound like it's the mass of the secondary! Perhaps `m1`, or `ma`?

**Comment by henry-ngo** [comment]
I called it m1 now and put a comment to say it's the mass of the primary star. Given the purpose of this package, I think we can assume that in most cases, m1 will be a star (but I suppose we can use this code to calculate a binary(!) planet haha)

**Comment by rjderosa** [comment]
Or black hole binaries!

**Pull request merged**
